/*
 * NBCParameters.java
 *
 * Created on 19 maj 2005, 18:52
 */

package clusterapp.view;
import javax.swing.JFrame;

import clusterapp.model.api.IClusteringParameters;
import java.awt.Dimension;
import javax.swing.JPanel;
import java.awt.GridBagLayout;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.FlowLayout;
import javax.swing.JTextField;
import javax.swing.JLabel;
import java.awt.GridLayout;
import java.awt.Color;

/**
 *
 * @author  pl
 */
public class LvaNbcParametersFrame extends javax.swing.JDialog {

	public static int res = -1;
	IClusteringParameters parameters;

	/** Creates new form NBCParameters */
//	public ParametersFrame() {
//		initComponents();
//	}
	
	public LvaNbcParametersFrame(IClusteringParameters params) {
		initComponents();
		this.parameters = params;
		this.jTextAreaK.setText(parameters.getValue("k"));
		jTextAreaK.setSelectionStart(0);
		jTextAreaK.setSelectionEnd(jTextAreaK.getText().length());
		int width = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
		int height = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
		
		this.setLocation((int)width/2 - (int)this.getSize().width/2,
				(int)height/2 - (int)this.getSize().height/2);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setContentPane(getJPanel());
        this.setTitle("Set parameters");
        this.setSize(new Dimension(277, 158));
        jButton1.setText("OK");
        jButton1.setOpaque(false);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jPanel1.add(jButton1, null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
		res = 0;
		//MainWindow.k = new Integer(this.jTextArea1.getText()).intValue();
		parameters.setValue("k", this.jTextAreaK.getText());
		parameters.setValue("l", this.jTextAreaL.getText());
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
			this.dispose();
	}//GEN-LAST:event_jButton2ActionPerformed
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
	private JPanel jPanel = null;
	private JPanel jPanel3 = null;
	private JTextField jTextAreaK = null;
	private JLabel jLabel = null;
	private JPanel jPanel2 = null;
	private JPanel jPanel4 = null;
	private JLabel jLabel2 = null;
	private JPanel jPanel5 = null;
	private JLabel jLabel3 = null;
	private JTextField jTextAreaL = null;
	/**
	 * This method initializes jPanel	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel() {
		if (jPanel == null) {
			jPanel = new JPanel();
			jPanel.setLayout(new BorderLayout());
			jPanel.add(jPanel1, BorderLayout.SOUTH);
			jPanel.add(getJPanel3(), BorderLayout.CENTER);
		}
		return jPanel;
	}

	/**
	 * This method initializes jPanel3	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel3() {
		if (jPanel3 == null) {
			GridLayout gridLayout = new GridLayout();
			gridLayout.setRows(3);
			gridLayout.setColumns(1);
			jLabel = new JLabel();
			jLabel.setText("k =");
			jPanel3 = new JPanel();
			jPanel3.setLayout(gridLayout);
			jPanel3.add(getJPanel4(), null);
			jPanel3.add(getJPanel2(), null);
			jPanel3.add(getJPanel5(), null);
		}
		return jPanel3;
	}

	/**
	 * This method initializes jTextAreaK	
	 * 	
	 * @return javax.swing.JTextField	
	 */
	private JTextField getJTextAreaK() {
		if (jTextAreaK == null) {
			jTextAreaK = new JTextField();
			jTextAreaK.setPreferredSize(new Dimension(25, 20));
			jTextAreaK.setText("22");
		}
		return jTextAreaK;
	}

	/**
	 * This method initializes jPanel2	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel2() {
		if (jPanel2 == null) {
			jPanel2 = new JPanel();
			jPanel2.setLayout(new FlowLayout());
			jPanel2.add(jLabel, null);
			jPanel2.add(getJTextAreaK(), null);
		}
		return jPanel2;
	}

	/**
	 * This method initializes jPanel4	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel4() {
		if (jPanel4 == null) {
			jLabel2 = new JLabel();
			jLabel2.setText("NBC");
			jPanel4 = new JPanel();
			jPanel4.setLayout(new FlowLayout());
			jPanel4.setBackground(Color.cyan);
			jPanel4.add(jLabel2, null);
		}
		return jPanel4;
	}

	/**
	 * This method initializes jPanel5	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel5() {
		if (jPanel5 == null) {
			jLabel3 = new JLabel();
			jLabel3.setText("l =");
			jPanel5 = new JPanel();
			jPanel5.setLayout(new FlowLayout());
			jPanel5.add(jLabel3, null);
			jPanel5.add(getJTextAreaL(), null);
		}
		return jPanel5;
	}

	/**
	 * This method initializes jTextAreaL	
	 * 	
	 * @return javax.swing.JTextField	
	 */
	private JTextField getJTextAreaL() {
		if (jTextAreaL == null) {
			jTextAreaL = new JTextField();
			jTextAreaL.setPreferredSize(new Dimension(25, 20));
			jTextAreaL.setText("50");
		}
		return jTextAreaL;
	}
	
}  //  @jve:decl-index=0:visual-constraint="41,-10"
