/*
 * MainWindow.java
 *
 * Created on 13 maj 2005, 10:21
 */

package clusterapp.view;

import java.util.*;
import java.text.*;
import java.awt.*;
import java.io.*;

import javax.swing.JOptionPane;
import javax.swing.UIManager;

import clusterapp.controller.ClusteringController;
import clusterapp.controller.DataSourceManager;
import clusterapp.model.api.IClusteringData;
import clusterapp.model.nbc.NBCLVA;
import lvaindex.vafile.ISpatialObject;
import java.awt.Dimension;

/**
 *
 * @author  pl
 */
public class MainWindow extends javax.swing.JFrame implements IClusteringObserver {
	
	public ClusteringController cc;
	AlgorithmsFrame af;
	
	//static int k = 22;
    
    public static ArrayList wnds = new ArrayList();
    public static int activeWnd = -1;
    
    MainWindow thisFrame;
    DataSourceFrame ds;
    DataSourceManager dsm;
    
    /** Creates new form MainWindow */
    public MainWindow() {
    	
        initComponents();
        thisFrame = this;

    }
    
    public void createFrames()
    {
        af = new AlgorithmsFrame(this);
        dsm = new DataSourceManager(this);
        ds = new DataSourceFrame(this, dsm);        
    }
    
    public void setFramesVisible(boolean visible)
    {
        af.setVisible(visible);
        ds.setVisible(visible);    	
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8a = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        this.setContentPane(jMenuItem7);
        this.setSize(new Dimension(640, 240));
        setTitle("Clustering");
        log.setPreferredSize(new java.awt.Dimension(300, 200));
        jScrollPane1.setViewportView(log);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("New");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem3);

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuItem6.setText("Save");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem6);

        /*jMenuItem7.setText("Close");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem7);*/

        jMenu1.add(jSeparator1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Utilities");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Add noise");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });

        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(""));
        //jMenuItem5.setText("Clear clusters");
        //jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Algorithms");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent e) {
        		if ( af == null )
        		{
        			af = new AlgorithmsFrame(thisFrame);
        		}
        		
        		if (af.isVisible())
        		{
        			af.setVisible(false);
        		}
        		else
        		{
        			af.setVisible(true);
        		}
        	}
        });
        
        jMenuItem8a.setText("IndicesTest");
        jMenuItem8a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8aActionPerformed(evt);
            }
        });


        jMenuItem8.setText("NBC (RTree)");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });

        jMenuItem9.setText("NBC (LVA)");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        
        jMenuItem10.setText("NBC (VAFile)");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });

        jMenu3.add(jMenuItem8a);
        
        jMenu3.add(jMenuItem8);
        
        jMenu3.add(jMenuItem9);
        
        jMenu3.add(jMenuItem10);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed
    
    private void jMenuItem8aActionPerformed(java.awt.event.ActionEvent evt)
    {
    	if (activeWnd == -1) {
    		noDataFrameSelected();
    		return;
    	}
    	cc = new ClusteringController();
    	cc.addObserver(this);
    	DataView2D dv = (DataView2D) this.wnds.get(activeWnd);
    	cc.setGraphics(dv.getGraphics());
    	
    	String algorithm = "IndicesTest";
    	cc.setDataSource(dv);
    	cc.addObserver(dv);    	
    	cc.run(algorithm);
    }

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
// TODO add your handling code here:
        
    	if (activeWnd == -1) {
    		noDataFrameSelected();
    		return;
    	}
    	
    	// TODO
    	cc = new ClusteringController();
    	cc.addObserver(this);
    	DataView2D dv = (DataView2D) this.wnds.get(activeWnd);
    	cc.setGraphics(dv.getGraphics());
    	
    	//String algorithm = "NBC";
    	String algorithm = "NBCRTree";
    	cc.setDataSource(dv);
    	cc.addObserver(dv);    	
    	cc.run(algorithm);
    	
    	//cc.run("NBC2");
    	
    	// TODO
    	/*
		NBCParameters nbcp = new NBCParameters(this);
		nbcp.show();
		if (nbcp.res == -1)
			return;

        DataView dv = (DataView) this.wnds.get(activeWnd);

        // Starting NBC...
        
		//System.out.println("Starting NBC");
		ListIterator li = dv.al.listIterator();
		ArrayList<ISpatialObject> iso = new ArrayList<ISpatialObject>();
		while(li.hasNext()) {
			PointView p = (PointView) li.next();
			p.reset();
			li.set(p);
			iso.add( new RTreeSpatialObject( p.m_pCoords ));
		}
		System.out.println("Creating nbc");
		dv.repaint();		
		
        //NBC nbc = new NBC(iso, k, dv.nDim, this);
		NBC2 nbc = new NBC2(iso, k, dv.nDim, this);
        
        dv.al.clear();
		for( ISpatialObject so:iso )
		{
			RTreeSpatialObject rtp = (RTreeSpatialObject) so;
			PointView p = new PointView( rtp.m_pCoords, rtp.c );
			dv.al.add( p );
		}
        
		dv.repaint();
		*/
        // Reloading data: GUI -> NBC
        // Performing analysis
		
        // Reloading data NBC -> GUI
    }//GEN-LAST:event_jMenuItem8ActionPerformed
    
    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
    	        
    	    	if (activeWnd == -1) {
    	    		noDataFrameSelected();
    	    		return;
    	    	}
    	    	
    	    	cc = new ClusteringController();
    	    	cc.addObserver(this);
    	    	DataView2D dv = (DataView2D) this.wnds.get(activeWnd);
    	    	cc.setGraphics(dv.getGraphics());
    	    	
    	    	String algorithm = "NBCLVA";
    	    	cc.setDataSource(dv);
    	    	cc.addObserver(dv);    	
    	    	cc.run(algorithm);
    	    	

    	    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
    	if (activeWnd == -1) {
    		noDataFrameSelected();
    		return;
    	}
    	
    	cc = new ClusteringController();
    	cc.addObserver(this);
    	DataView2D dv = (DataView2D) this.wnds.get(activeWnd);
    	cc.setGraphics(dv.getGraphics());
    	
    	String algorithm = "NBCVAFile";
    	cc.setDataSource(dv);
    	cc.addObserver(dv);    	
    	cc.run(algorithm);
    	

    }
    
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
// TODO add your handling code here:
        //System.out.println("Saving...");
    	
    	if (activeWnd == -1) {
    		noDataFrameSelected();
    		return;
    	}
    	
        String title = "Save...";
       
        String f = "aa";
        FileDialog fd = new FileDialog(this, title, FileDialog.SAVE);
        //fd.setFile(fileType);
        fd.setFile("my-file");
        fd.setDirectory("");
        fd.setLocation(50, 50);
        fd.show();
        //System.out.println(fd.getFile());
        //System.out.println(fd.getDirectory());
        
        DataView2D dv = (DataView2D) this.wnds.get(activeWnd);
         
        try {
            FileOutputStream fout =  new FileOutputStream(fd.getDirectory() + "/" + fd.getFile());
            // JDK1.1+
            BufferedWriter myOutput = new BufferedWriter(new OutputStreamWriter(fout));
             // JDK1.02   
             // DataInputStream myInput = new DataInputStream(fin);
            String thisLine;
            // ommiting 2 first lines

            /*myOutput.write("NumberOfObjects " + dv.al.size() + "\r\n");
            myOutput.write("NumberOfAttributes " + dv.nDim + "\r\n");*/

            for (int i = 0; i < dv.al.size(); i++) {
               PointView point  = (PointView) dv.al.get(i);
               System.out.println(point.toString());
               myOutput.write(point.toLine());
               myOutput.write("\n");
               //System.out.println( "ERROR" );
            }
            myOutput.flush();
            
        } catch (Exception e) {
           e.printStackTrace();
        }

         

        //return fd.getFile();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
// TODO add your handling code here:
        
    	if (activeWnd == -1) {
    		noDataFrameSelected();
    		return;
    	}
        
        DataView2D dv = (DataView2D) this.wnds.get(activeWnd);
        
        int noiseSize = 50;
        Random r = new Random();
		int realNoiseSize = 0;
        
        for(int i = 0; i < noiseSize; i++) {
            
            double []coords = new double[2];
            coords[0] = (double) (r.nextInt(dv.getSize().width));
            coords[1] = (double) (r.nextInt(dv.getSize().height));
            PointView point = new PointView(coords, -1);
            
            if (!dv.al.contains(point)) {
                dv.al.add(point);
				realNoiseSize++;
                dv.paintPoint(dv.getGraphics(), dv.al.size() - 1);
            }
        }
        
        this.addLog("Added noise: " + realNoiseSize + " points, total number of points:" + dv.al.size());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
// TODO add your handling code here:
        DataView2D dv = new DataView2D(this);
        wnds.add(dv);
        activeWnd = wnds.indexOf(dv);
        //System.out.println("-aktywne okno: " + activeWnd);
        dv.setLocation(this.getLocation().x, this.getLocation().y + this.getSize().height);
        dv.setSize(new Dimension(640,480));
        dv.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)
    {
		// Creating new window...
		DataView2D dv = new DataView2D(this);
		wnds.add(dv);
		activeWnd = wnds.indexOf(dv);

		String title = "Open...";

		FileDialog fd = new FileDialog(this, title, FileDialog.LOAD);
		fd.setLocation(50, 50);
		fd.setVisible(true);

		try {
			FileInputStream fin = new FileInputStream(fd.getDirectory() + "/"
					+ fd.getFile());
			BufferedReader myInput = new BufferedReader(new InputStreamReader(
					fin));
			String thisLine;
			int nAttr = -1;// new Integer(sNumAttr[1]).intValue();
			dv.nDim = nAttr; // trochê z³e nazewnictwo :(
			while ((thisLine = myInput.readLine()) != null) {
				// System.out.println(thisLine);
				String s[] = thisLine.split(";");
				if (s.length <= 1) {
					s = thisLine.split(":");
				}

				if (nAttr == -1) {
					nAttr = s.length - 1;
				}

				if ((s.length - 1) != nAttr) {
					throw new Exception("Incorrect number of attributes: "
							+ (s.length - 1) + " != " + nAttr);
				}

				double[] coords = new double[nAttr];

				for (int i = 0; i < nAttr; i++)
					coords[i] = new Double(s[i]).doubleValue();

				PointView point = new PointView(coords, -1);

				dv.al.add(point);
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

		dv.setVisible(true);

	}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
    	
    	UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
    	
    	MainWindow mw = new MainWindow();
    	mw.setSize(new Dimension(640, 240));
    	mw.createFrames();
    	mw.setVisible(true);
    	mw.setFramesVisible(true);
    	
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8a;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private static javax.swing.JTextPane log;
    // End of variables declaration//GEN-END:variables
    
    public void addLog(String log)
    {
        Date today = new Date();
        String DATE_FORMAT = "yyyy-MM-dd HH:mm:ss";
        //java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat(DATE_FORMAT);
        SimpleDateFormat formatter = new SimpleDateFormat(DATE_FORMAT);
        String now = formatter.format(today);
        this.log.setText(MainWindow.log.getText() + now + "\t" + log + "\r\n");
    }

    public void noDataFrameSelected()
    {
    	JOptionPane.showMessageDialog(this, "The data frame was not selected.\nSelect or create a new data frame\n(Choose 'New' from the 'File' menu).");
    }

	@Override
	public void handleNotify(IClusteringData data) {
		// ignore
	}

	@Override
	public void handleNotify(String message) {
		// TODO Auto-generated method stub
		System.out.println(message);
		//addLog(message);
	}

	@Override
	public void handleNotify(Object object) {
		// TODO Auto-generated method stub
	}

}  //  @jve:decl-index=0:visual-constraint="10,10"
