/*
 * NBCParameters.java
 *
 * Created on 19 maj 2005, 18:52
 */

package clusterapp.view;
import javax.swing.JFrame;

import clusterapp.model.api.IClusteringParameters;
import java.awt.Dimension;
import javax.swing.JPanel;
import java.awt.GridBagLayout;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.FlowLayout;
import javax.swing.JTextField;
import javax.swing.JLabel;

/**
 *
 * @author  pl
 */
public class ParametersFrame extends javax.swing.JDialog {

	public static int res = -1;
	IClusteringParameters parameters;

	/** Creates new form NBCParameters */
//	public ParametersFrame() {
//		initComponents();
//	}
	
	public ParametersFrame(IClusteringParameters params) {
		initComponents();
		this.parameters = params;
		this.jTextArea1.setText(parameters.getValue("k"));
		int width = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
		int height = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
		
		this.setLocation((int)width/2 - (int)this.getSize().width/2,
				(int)height/2 - (int)this.getSize().height/2);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setContentPane(getJPanel());
        this.setTitle("Set parameters");
        this.setSize(new Dimension(277, 97));
        jButton1.setText("OK");
        jButton1.setOpaque(false);
        jButton1.setPreferredSize(new java.awt.Dimension(75, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jPanel1.add(jButton1, null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jButton2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
		res = 0;
		//MainWindow.k = new Integer(this.jTextArea1.getText()).intValue();
		parameters.setValue("k", this.jTextArea1.getText());
		this.dispose();
	}//GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
			this.dispose();
	}//GEN-LAST:event_jButton2ActionPerformed
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
	private JPanel jPanel = null;
	private JPanel jPanel3 = null;
	private JTextField jTextArea1 = null;
	private JLabel jLabel = null;
	/**
	 * This method initializes jPanel	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel() {
		if (jPanel == null) {
			jPanel = new JPanel();
			jPanel.setLayout(new BorderLayout());
			jPanel.add(jPanel1, BorderLayout.SOUTH);
			jPanel.add(getJPanel3(), BorderLayout.CENTER);
		}
		return jPanel;
	}

	/**
	 * This method initializes jPanel3	
	 * 	
	 * @return javax.swing.JPanel	
	 */
	private JPanel getJPanel3() {
		if (jPanel3 == null) {
			jLabel = new JLabel();
			jLabel.setText("k =");
			jPanel3 = new JPanel();
			jPanel3.setLayout(new FlowLayout());
			jPanel3.add(jLabel, null);
			jPanel3.add(jLabel1, null);
			jPanel3.add(getJTextArea1(), null);
		}
		return jPanel3;
	}

	/**
	 * This method initializes jTextArea1	
	 * 	
	 * @return javax.swing.JTextField	
	 */
	private JTextField getJTextArea1() {
		if (jTextArea1 == null) {
			jTextArea1 = new JTextField();
			jTextArea1.setPreferredSize(new Dimension(25, 20));
		}
		return jTextArea1;
	}
	
}  //  @jve:decl-index=0:visual-constraint="41,-10"
